CREATE TABLE Authors (
 ID SERIAL PRIMARY KEY,
 Name VARCHAR(100)
);

CREATE TABLE Users (
   ID SERIAL PRIMARY KEY,
   Name VARCHAR(100),
   Address VARCHAR(255)
);

CREATE TABLE Books (
 ISBN VARCHAR(255) PRIMARY KEY,
 Title VARCHAR(255),
 Author INT,
 Publisher INT,
 Category INT,
 FOREIGN KEY (Author) REFERENCES Authors(ID)
);

CREATE TABLE Rents (
 ID SERIAL PRIMARY KEY,
 User_ID INT,
 Book VARCHAR(255),
 Rental_Date DATE,
 Return_Date DATE,
 FOREIGN KEY (User_ID) REFERENCES Users(ID),
 FOREIGN KEY (Book) REFERENCES Books(ISBN)
);

CREATE TABLE Reservations (
 ID SERIAL PRIMARY KEY,
 User_ID INT,
 Book VARCHAR(255),
 Rental_Date DATE,
 FOREIGN KEY (User_ID) REFERENCES Users(ID),
 FOREIGN KEY (Book) REFERENCES Books(ISBN)
);

CREATE TABLE Publishers (
 ID SERIAL PRIMARY KEY,
 Name VARCHAR(255),
 Address VARCHAR(255)
);

CREATE TABLE Categories (
 ID SERIAL PRIMARY KEY,
 Category VARCHAR(255)
);

CREATE TABLE Ratings (
 ID SERIAL PRIMARY KEY,
 User_ID INT,
 Book VARCHAR(255),
 Rating INT,
 FOREIGN KEY (User_ID) REFERENCES Users(ID),
 FOREIGN KEY (Book) REFERENCES Books(ISBN)
);

CREATE TABLE Rents_History (
 ID SERIAL PRIMARY KEY,
 User_ID INT,
 Book VARCHAR(255),
 Rental_Date DATE,
 Return_Date DATE,
 FOREIGN KEY (User_ID) REFERENCES Users(ID),
 FOREIGN KEY (Book) REFERENCES Books(ISBN)
);
